language: rust

rust:
  - 1.40.0

before_cache:
  - cargo install cargo-tarpaulin

script:
  - cargo build --verbose --all
  - sudo env "PATH=$PATH" RUST_BACKTRACE=1 cargo test --verbose --all

after_success:
  - sudo env "PATH=$PATH" cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID